### ISSUE TITLE
Generator with parameter -n 0 does not work anymore

### ISSUE THREAD

**Issue by ahuangfeng** [insa-unyte/scapy#17]
`sudo python3 src/main.py -n 0` should sent UDP-notif indefinitely, but a stacktrace of casting is showed.
Bug after merge of #16

**Comment by Axelitooo** [comment]
I had changed the "while" into a "for" when iterating on message_amount. But when the argument n is set at 0, it becomes float(`int`), and you can't iterate on that. So I reset my change.
